### ISSUE TITLE
mistake in convolution example

### ISSUE THREAD

**Issue by mardybumsz** [debber1/Systemen#4]
![image](https://user-images.githubusercontent.com/121303742/209466575-9f6a2226-cb8c-4938-a5f5-9367dba0d5f9.png)

Integral should look like this:
![image](https://user-images.githubusercontent.com/121303742/209466572-85b82d1e-ffe4-4bf1-ad75-0d3561f891f7.png)

**Comment by debber1** [comment]
Fixed by #5 Thanks again :)
